# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 6432:5432

    steps:
      - name: Set up PostgeSQL
        run: |
          psql -d postgresql://localhost:6432/eav-test -c "CREATE SCHEMA IF NOT EXISTS public;"
          psql -d postgresql://localhost:6432/eav-test -c "CREATE SCHEMA IF NOT EXISTS security;"

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Run code coverage verification
        run: ./gradlew testCoverage